name: Deploy .NET 6 API to IIS (Self-Hosted)

on:
  push:
    branches:
      - main   # deploy only from main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted  # local Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore ./WeatherAPI.sln

      - name: Build
        run: dotnet build ./WeatherAPI.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./WeatherAPI.csproj -c Release -o ./publish --runtime win-x64 --self-contained false
        
      - name: Stop IIS site
        run: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "MyApiAppPool"

      - name: Deploy to IIS folder
        run: |
          echo "Deploying to IIS folder..."
          robocopy ".\publish" "C:\inetpub\myapi\" /MIR /R:2 /W:5

      - name: Start IIS site
        run: |
          Import-Module WebAdministration
          Start-WebAppPool -Name "MyApiAppPool"  

