name: Deploy to Local IIS
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: self-hosted   # Your GitHub self-hosted runner (Windows)

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 3. Restore dependencies
      - name: Restore dependencies
        shell: cmd
        run: dotnet restore WeatherAPI.csproj


      # 4. Build project
      - name: Build
        shell: cmd
        run: dotnet build --configuration Release --no-restore

      # 5. Publish project
      - name: Publish
        shell: cmd
        run: dotnet publish -c Release -o ./publish


      # 7. Deploy files to IIS folder
      - name: Deploy to IIS
        run: |          
          $deployPath = "E:\myapi"
          Remove-Item -Recurse -Force "$deployPath\*"
          Copy-Item -Path "./publish/*" -Destination $deployPath -Recurse
        shell: powershell
        