name: Deploy .NET 6 API to IIS (Self-Hosted)

on:
  push:
    branches:
      - main   # deploy only from main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted  # local Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore ./WeatherAPI.sln

      - name: Build
        run: dotnet build ./WeatherAPI.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./WeatherAPI.csproj -c Release -o ./publish

      - name: Deploy to IIS folder
        run: |
          echo "Deploying to IIS folder..."
          if exist "C:\inetpub\myapi" rmdir /s /q "C:\inetpub\myapi"
          mkdir "C:\inetpub\myapi"
          xcopy /E /I /Y ".\publish\*" "C:\inetpub\myapi\"
