name: Deploy .NET 6 API to IIS (Self-Hosted)

on:
  push:
    branches:
      - main   # deploy only from main branch

jobs:
  build:
    runs-on: self-hosted  # local Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore ./WeatherAPI.sln

      - name: Build
        run: dotnet build ./WeatherAPI.sln --configuration Release --no-restore
  
  publish:
    needs: build
    runs-on: self-hosted  # local Windows runner    
    steps:
      - name: Publish
        run: dotnet publish ./WeatherAPI.csproj -c Release -o ./publish --runtime win-x64 --self-contained false
  
  IIS_Stop:
    needs: publish
    runs-on: self-hosted  # local Windows runner    
    steps:      
      - name: Stop IIS POOL
        run: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "MyApiAppPool"  

      - name: Stop IIS Website
        run: |
          Import-Module WebAdministration
          Stop-Website -Name "myapi"    

      - name: Introduce Delay
        run: sleep 10 # Pauses execution for 10 seconds     

  deploy:
    needs: IIS_Stop
    runs-on: self-hosted

    steps:      
      - name: Deploy to IIS folder
        run: |
          echo "Deploying to IIS folder..."
          xcopy ".\publish\*" "C:\inetpub\myapi\" /E /I /Y 

  IIS_Start:
    needs: deploy
    runs-on: self-hosted
    steps:         
      - name: Start IIS POOL
        run: |
          Import-Module WebAdministration
          Start-WebAppPool -Name "MyApiAppPool" 

      - name: Start IIS Website
        run: |
         Import-Module WebAdministration
         Start-Website -Name "myapi"    

